### ISSUE TITLE
Edit Inputs

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#18]
Users should not be forced to enter negative values. Let them enter values and negate them if they are >0.

**Comment by pointbazaar** [comment]
good point.

**Comment by pointbazaar** [comment]
bda891959b4a511181c0ac088cdf9aecec2624f8

fixed it for the expenses section of the application. 
Thanks again for pointing it out. :)
You are right, it is easier for users and users have to type less

**Comment by pointbazaar** [comment]
it will be deployed with the next deployment, it is not live now.
