### ISSUE TITLE
Change font-sizes

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#19]
Font-sizes in Octofinsights are not set to rem values which makes them very small on mobile devices and destroys Bootstraps responsive features.

**Comment by pointbazaar** [comment]
yes. i did not set any font sizes. i still have to learn how to do that in the bootstrap way

**Comment by maste150hhu** [comment]
In general all your contents of a page should be placed in a DIV inside of the body in BootStrap. Define a font-size with the rem-unit for the body or for the DIV used as a "wrapper" for BootStrap

**Comment by pointbazaar** [comment]
c47d64e531121077efa12b1c774123cb112858cd

this should have fixed some stuff.
