### ISSUE TITLE
Disable "last-used" functionality in forms

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#20]
When entering anything in any form, the webbrowser's prediction steps in and shows everything you have entered on this site before. This shouldn't be disabled client-side, but on server-side. 

You could add a functionality which lists for example 2-3 prediction right below the form, but not everything you entered before.

**Comment by pointbazaar** [comment]
prediction is a good idea. but i have no idea how to remove the predictions on the client side.

like with github issues, there are predictions so you do not make the same issue twice. 
It would be interesting to show the user sales which have already been made when they are entering a sale.

**Comment by maste150hhu** [comment]
W3School seems to have the answer [https://www.w3schools.com/howto/howto_js_autocomplete.asp](url)

Demo: [https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_autocomplete](url)

**Comment by pointbazaar** [comment]
i am unsure for which fields a server side autocomplete would be useful for the application.
some fields are <select> already and autocomplete by default. 
also this would probably cause many queries on the DB if we wanted to autocomplete 
stuff thats already in the db.
For now i will stick with the browser provided autocomplete.
