### ISSUE TITLE
Optimize style of expenses

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#39]
![image](https://user-images.githubusercontent.com/49523050/63006423-ce6e4280-be7e-11e9-9c29-96e0435c3b5a.png)

The text should be in the center of the row and the button should be a lot smaller

**Comment by pointbazaar** [comment]
i agree, the button wastes a lot of space. in general there is too much height per row.

**Comment by pointbazaar** [comment]
the rows in the table are smaller now, but not optimal.
also the buttons now have text instead of icons, for accessibility reasons.

Again, thanks for the issue. :+1: :100:
