### ISSUE TITLE
Insert button must be aligned to the input forms

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#40]
![image](https://user-images.githubusercontent.com/49523050/63006533-09707600-be7f-11e9-97e0-4a63c7cf3e0e.png)

![image](https://user-images.githubusercontent.com/49523050/63006558-15f4ce80-be7f-11e9-9eda-cc987ae81e7e.png)

As you can see in the images a lot of buttons have wrong height alignment or are not aligned at all

**Comment by pointbazaar** [comment]
![octofinsights_form](https://user-images.githubusercontent.com/15467505/70811816-af4cd680-1dc6-11ea-8172-264c2cd1f092.png)

looks better now.
/invoices still needs better UI but the invoices feature is not completed yet.

thanks for the issue.

**Comment by pointbazaar** [comment]
looks better now.

/invoices still looks bad but the feature is not complete

**Comment by pointbazaar** [comment]
![octofinsights_form](https://user-images.githubusercontent.com/15467505/70812006-0fdc1380-1dc7-11ea-956e-51c6562b2a43.png)
