### ISSUE TITLE
Not displaying graphs when using test-account and Microsoft Edge

### ISSUE THREAD

**Issue by maste150hhu** [vanautrui/octofinsights#44]
![Click me](https://user-images.githubusercontent.com/49523050/63419893-e6593f80-c405-11e9-8c40-1834ee4d3cf6.png)

**Comment by pointbazaar** [comment]
can you provide console output or network log? 
i suspect that chart.js could be using features not available in microsoft edge?

can you try a chart.js demo on another website?

thank you for the report :)

**Comment by maste150hhu** [comment]
You can close this, Microsoft will soon update the Microsoft Edge browser to the new one built in Chromium.
